<br>
<div id="index">
&nbsp;
	<div id="container">
		<div id="tabs">
			<ul>
				<li><a href="#gallery-tab">Gallery</a></li>
				<li><a href="#cloud">Cloud</a></li>
			</ul>
			<div id="gallery-tab">
				<div id="menusearch">
					<span class="label">Search Criteria</span>
					<div class="border">

						<form class="searchform" name="searchform">

						<div id="form">
								<input class="searchfield" id="target" name="search" type="text" value="" />
								<input class="searchbutton" type="button" value="Go" />
								<span class="more"><a href="#" onclick="advanced();">>> More</a></span>
						</div>

						<div id="common">
							Common
							<div class="toggles">
								<input type="checkbox" name="master" onchange="changed(this);"/>Master<br>
								<input type="checkbox" name="tileable" onchange="changed(this);"/>Tileable<br>
								<input type="checkbox" name="png" onchange="changed(this);"/>PNG Only<br>
							</div>
						</div>

						<div id="order">
							Order By
							<div class="toggles">
								<input type="checkbox" name="rating" onchange="changed(4);"/>Rating<br>
								<input type="checkbox" name="download" onchange="changed(5);"/>Download Count<br>
								<input type="checkbox" name="added" onchange="changed(6);"/>Date added<br>
							</div>
						</div>

						</form>
					</div>
				</div>

				<br>

				<div id="gallery">
				</div>	
			</div>

			<div id="Cloud">
			</div>
		</div>
	</div>

	<div id="footer">
		(C) 2012 The Public Texture Repository Project
	</div>
</div>

<div id="ending">
&nbsp;
</div>


