<?php
	echo $this->jQuery();
	$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle('Zend Framework Tutorial');
	echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>

	<link rel="stylesheet" href="/css/token-input.css" type="text/css" />
	<link rel="stylesheet" href="/css/token-input-facebook.css" type="text/css" />

	<script src="pubtex.js" type="text/javascript"></script>
	<script src="jquery.tokeninput.js" type="text/javascript"></script>
</head>

<body>
	<div id="header"> 
		<span id="logo">
			<img src="/images/logo2.png" />
		</span>

		<span id="banner">
		</span>

		<span id="padding">
		</span>
	</div>

	<div id="menu">
		<div class="menulink"><a href="/"><img src="/images/Home.png"/></a></div>
		<div class="menulink"><a href="/"><img src="/images/About.png" /></a></div>
		<div class="menulink"><a href="/"><img src="/images/News.png" /></a></div>
		<div class="menulink"><a href="/"><img src="/images/Contact.png"/></a></div>

		<div id="menusearch">
			<?php echo $this->searchForm(); ?>
		</div>

		<div class="menulogin">
			<?php echo $this->loggedInAs(); ?>
		</div>		

		<div style="clear: both;"></div><br>
	</div>

	<div id="content">
		<h1>
			<?php echo $this->escape($this->title); ?>
		</h1>

		<?php echo $this->layout()->content; ?>
	</div>

</body>
</html>

