<?php
	echo $this->jQuery();
	$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle('PubTex, Public Domain Media Database');
	echo $this->doctype();

	$request = Zend_Controller_Front::getInstance()->getRequest();
	$controller = $request->getControllerName();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<link rel="shortcut icon" href="favicon.ico" >
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>

	<script src="js/pubtex.js" type="text/javascript"></script>
  <?php 
		if($controller == 'index')
		{
			echo "	<script src=\"js/index.js\" type=\"text/javascript\"></script>";

			echo "	<link rel=\"stylesheet\" href=\"/css/token-input.css\" type=\"text/css\" />";
			echo "	<link rel=\"stylesheet\" href=\"/css/token-input-facebook.css\" type=\"text/css\" />";
			echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery.ad-gallery.css\">";

			echo "	<script src=\"js/jquery.ad-gallery.js\" type=\"text/javascript\"></script>";
			echo "	<script src=\"jquery.tokeninput.js\" type=\"text/javascript\"></script>";

		}

		if($controller == 'media-details')
		{
		}
	?>

	<script src="js/jquery.tokeninput.js" type="text/javascript"></script>
</head>

<body>
	<div id="header"> 
		<div class="logo">
			<img src="/images/PxGlow.xcf-PxLogo.png"/>
		</div>

		<div class="slogan">
			<img src="/images/PxGlow.xcf-TempSlogan.png"/>
		</div>

		<div class="separator">
			<img src="/images/PxGlow.xcf-Pasted Layer.png"/>	
		</div>

		<div class="menu">
			<div class="upper">
				<?php echo $this->loggedInAs(); ?>
			</div>

			<div class="lower">
				<div class="item">
					<img src="/images/about.png"/>
				</div>

				<div class="item">
					<img src="/images/legal.png"/>
				</div>

				<div class="item"> 
					<img src="/images/contact.png"/>
				</div>
			</div>
		</div>
	</div>

	<div style=\"clear: both;\"></div>

<?php echo $this->layout()->content; ?>

</body>
</html>

