<?php
	echo $this->jQuery();
	$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle('PubTex, Public Domain Media Database');
	echo $this->doctype();

	$request = Zend_Controller_Front::getInstance()->getRequest();
	$controller = $request->getControllerName();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<link rel="shortcut icon" href="favicon.ico" >
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>

	<script src="js/pubtex.js" type="text/javascript"></script>
  <?php 
		if($controller == 'index')
		{
			echo "	<script src=\"js/index.js\" type=\"text/javascript\"></script>";

			echo "	<link rel=\"stylesheet\" href=\"/css/token-input.css\" type=\"text/css\" />";
			echo "	<link rel=\"stylesheet\" href=\"/css/token-input-facebook.css\" type=\"text/css\" />";
			echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery.ad-gallery.css\">";

			echo "	<script src=\"js/jquery.ad-gallery.js\" type=\"text/javascript\"></script>";
			echo "	<script src=\"jquery.tokeninput.js\" type=\"text/javascript\"></script>";

		}

		if($controller == 'media-details')
		{
		}
	?>

	<script src="js/jquery.tokeninput.js" type="text/javascript"></script>
</head>

<body>


	<div id="header"> 
		<span id="logo">
			<img src="/images/logo.png" />
		</span>

		<span id="banner">
		</span>

		<span id="padding">
		</span>
	</div>

	<div id="menu">
		<div class="menulink"><a href="/"><img src="/images/Home.png"/></a></div>
		<div class="menulink"><a href="/"><img src="/images/About.png" /></a></div>
		<div class="menulink"><a href="/"><img src="/images/News.png" /></a></div>
		<div class="menulink"><a href="/"><img src="/images/Contact.png"/></a></div>

		<div id="menulogin">
			<?php echo $this->loggedInAs(); ?>
		</div>		

		<div style="clear: both;"></div><br>
	</div>

<?php echo $this->layout()->content; ?>

</body>
</html>

